# bitbucket-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitbucket
spec:
  selector:
    matchLabels:
      app: bitbucket
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: bitbucket
    spec:
      containers:
      - image: atlassian/bitbucket-server:latest
        name: bitbucket
        env:
        - name: JDBC_DRIVER
          value: org.postgresql.Driver
        - name: JDBC_URL
          value: jdbc:postgresql://postgres:5432/bitbucket
        - name: JDBC_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-user
        - name: JDBC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-password
        ports:
        - containerPort: 7990
          name: http
        - containerPort: 7999
          name: ssh
        volumeMounts:
        - name: bitbucket-storage
          mountPath: /var/atlassian/application-data/bitbucket
          subPath: bitbucket
      volumes:
      - name: bitbucket-storage
        persistentVolumeClaim:
          claimName: bitbucket-pv-claim