# postgres-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  # Use base64 to encode the PostgreSQL username and password
  postgres-user: [base64 encoded username]
  postgres-password: [base64 encoded password]